# Generated by Django 3.0.10 on 2020-11-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201117_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='taosent',
            name='tx_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
