# Generated by Django 3.0.10 on 2020-11-17 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_taosent_tx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taoreceived',
            name='migration_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.MigrationAddress'),
            preserve_default=False,
        ),
    ]
